describe('Form tests', () => {
    beforeEach(() => {
        cy.visit('/forms')
    })
    it('Test subscribe form', () => {
        cy.contains(/testing forms/i)
        cy.getDataTest('subscribe-form').find('input').as('subscribe-input')
        //cy.getDataTest('subscribe-form').find('input').type('nahuelrmaury@gmail.com')
        cy.get('@subscribe-input').type('nahuelrmaury@gmail.com')
        cy.contains(/Successfully subbed: nahuelrmaury@gmail.com!/i).should('not.exist')
        cy.getDataTest('subscribe-button').click()
        cy.contains(/Successfully subbed: nahuelrmaury@gmail.com!/i).should('exist')
        cy.wait(3000)
        cy.contains(/Successfully subbed: nahuelrmaury@gmail.com!/i).should('not.exist')
        cy.get('@subscribe-input').type('nahuelrmaury@gmail.io')
        cy.getDataTest('subscribe-button').click()
        cy.contains(/invalid email: nahuelrmaury@gmail.io!/i).should('exist')
        cy.wait(3000)
        cy.contains(/invalid email: nahuelrmaury@gmail.io!/i).should('not.exist')
        cy.getDataTest('subscribe-button').click()
        cy.contains(/fail!/i).should('exist')
        cy.wait(3000)
        cy.contains(/fail!/i).should('not.exist')
    })
})